### ISSUE TITLE
Create ci.env for each build so artifacts can be fed to cross-cloud

### ISSUE THREAD

**Issue by hh** [cncf/cross-cloud#16]

**Comment by hh** [comment]
For now we only need ci.env for Kubernetes, as it's the only artifact we are using with cross-cloud/provision.sh

The ci.vars for k8s jobs will look like:
```
export TF_VAR_kubelet_image_url=registry.cncf.ci/kubernetes/kubernetes/hyperkube-amd64
export TF_VAR_kubelet_image_tag=ci-master.job.3648
```

```yaml
image: docker:17.05.0
stages:
  - build
before_script:
  - apk update
  - apk add bash tar rsync git curl make file
  - sed -i -e '/ linux\/arm/ s/^/#/' hack/lib/golang.sh 
  - sed -i -e '/ linux\/s390/ s/^/#/' hack/lib/golang.sh 
  - sed -i -e '/ linux\/386/ s/^/#/' hack/lib/golang.sh 
  - sed -i -e '/ linux\/ppc64le/ s/^/#/' hack/lib/golang.sh 
  - sed -i -e '/ darwin\/amd64/ s/^/#/' hack/lib/golang.sh 
  - sed -i -e '/ darwin\/386/ s/^/#/' hack/lib/golang.sh 
  - sed -i -e '/ windows\/386/ s/^/#/' hack/lib/golang.sh 
  - sed -i -e '/ windows\/amd64/ s/^/#/' hack/lib/golang.sh 
  - sed -i -e 's/kube::release::package_tarballs//g' ./build/release.sh
build:
  stage: build
  variables:
    KUBE_DOCKER_REGISTRY: "${CI_REGISTRY_IMAGE}"
    KUBE_DOCKER_IMAGE_TAG: "${CI_COMMIT_REF_SLUG}.job.${CI_JOB_ID}"
    KUBE_RELEASE_RUN_TESTS: "n"
    KUBE_FASTBUILD: "false"
    KUBE_VERBOSE: "0"
    FEDERATION: "false"
  script:
    - ./build/release.sh || sleep 99999
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker push "$CI_REGISTRY_IMAGE/hyperkube-amd64:$KUBE_DOCKER_IMAGE_TAG"
    - cp -a _output/dockerized/bin/linux/amd64 linux-amd64
    - echo export TF_VAR_kubelet_image_url="$CI_REGISTRY_IMAGE/hyperkube-amd64" > ci.vars
    - echo export TF_VAR_kubelet_image_tag="$KUBE_DOCKER_IMAGE_TAG" >> ci.vars
  artifacts:
    name: "${CI_JOB_NAME}.${CI_PIPELINE_ID}.${CI_JOB_ID}"
    expire_in: 1 weeks
    paths:
      - ci.vars
      - linux-amd64
```
